option(PROFILE "Profile with google perftools" OFF)
#option(COVERAGE "Coverage" OFF)
option(ENABLE_VALGRIND "Tests under valgring (test-valgrind target)" ON)
option(ENABLE_ASAN  "Enable ASAN" OFF)
option(ENABLE_UBSAN "Enable UBSAN" OFF)
option(ENABLE_TSAN  "Enable TSAN" OFF)
option(EXPORT_COMPILE "Export compile database" OFF)
option(BUILD_TESTING "Build tests" ON)
